version: '3'
services: 
  app:
    build: 
      context: .
      dockerfile: dockerfile.dev
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/frontend
  tests:
    build: 
      context: .
      dockerfile: dockerfile.dev
    volumes: 
      - .:/usr/frontend
    command: ['npm', 'run', 'test']